# Generated by Django 5.0.1 on 2024-02-02 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='1')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='2')),
                ('phone', models.CharField(max_length=50, verbose_name='3')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='4')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='5')),
                ('description', models.TextField(blank=True, verbose_name='6')),
            ],
        ),
    ]
